name: Azure Deploy
on:
  push:
    branches:
      - main # change to main if needed
jobs:
  build-deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group # optional: ensure only one action runs at a time
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login Azure registry'
        uses: azure/docker-login@v1
        with:
          login-server: comp7940registry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Push image to registry' 
        run: |
          docker build . -t comp7940registry.azurecr.io/comp7640-project-test:${{ github.sha }}
          docker push comp7940registry.azurecr.io/comp7640-project-test:${{ github.sha }}

      - name: 'Run Azure web app deploy action'
        uses: azure/webapps-deploy@v3
        with:
          app-name: comp7940project
          package: comp7940registry.azurecr.io/comp7640-project-test

      - name: 'Logout' 
        run: |
          az logout

